### ISSUE TITLE
Update semantic-release in peerDependencies to v17

### ISSUE THREAD

**Issue by SPGoding** [momocow/semantic-release-gitmoji#14]
Release notes for v16: https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0  
Release notes for v17: https://github.com/semantic-release/semantic-release/releases/tag/v17.0.0  

Those breaking changes don't seem to affect this package, though I'm not really sure.

Thanks for making such an awesome plugin!

**Comment by momocow** [comment]
Thanks for reminding me that semantic-release is v17 now!

Let me take a look at the release notes first then I'll try to upgrade the dependencies including semantic-release.
