### ISSUE TITLE
ability to add handlebars helpers

### ISSUE THREAD

**Issue by scottnath** [momocow/semantic-release-gitmoji#2]
Hi @momocow 

Would you be open to adding the ability to add a user's helpers. Could be possible by adding a section similar to your [registerPartials](https://github.com/momocow/semantic-release-gitmoji/blob/master/lib/release-notes.js#L103) section for helpers. This would then need a new config for an array of helpers.

**Comment by momocow** [comment]
Reasonable request. It should be included in the next release.

Thanks for your feedback.

**Comment by momocow** [comment]
This feature has been available since [v1.2.0](https://github.com/momocow/semantic-release-gitmoji/releases/tag/v1.2.0). 🎉 

Closed due to the new release.
If you have any questions or there is any mistake, feel free to reopen the issue or file a new one. :)

**Comment by scottnath** [comment]
fantastic! Thank you!
