### ISSUE TITLE
Update semantic-release in peerDependencies to v18

### ISSUE THREAD

**Issue by nwesthoff** [momocow/semantic-release-gitmoji#34]
Release notes: https://github.com/semantic-release/semantic-release/releases/tag/v18.0.0

Might it be a good option to set `>= 17.0.0` in `peerDependencies`, so all new versions will at least not throw an error while installing. Unless you don't mind doing the manual update every time semantic-release updates, of course. 

Thanks!

**Comment by momocow** [comment]
Thanks for reminding me!

I prefer stick to the major version as what we currently do, which is what semantic versioning suggests.

But! I think I can set up a periodic GitHub Action to check the version of `semantic-release` and update the `peerDependencies`.

**Comment by dgilperez** [comment]
And v19 was released, with some security fixes :)

**Comment by momocow** [comment]
Fixed by #35 with peer dependency set to semantic-release@<20.
