### ISSUE TITLE
overwriting config for custom templates does seem to work

### ISSUE THREAD

**Issue by thomasaull** [momocow/semantic-release-gitmoji#4]
With the following config:

```
const fs = require('fs')
const path = require('path')
const { promisify } = require('util')
const readFileAsync = promisify(fs.readFile)

const TEMPLATE_DIR = path.join(__dirname, 'config')

module.exports = {
  plugins: [
    'semantic-release-gitmoji',
    {
      releaseNotes: {
        template: readFileAsync(
          path.join(TEMPLATE_DIR, 'my-default-template.hbs')
        ),
        partials: {
          commitTemplate: readFileAsync(
            path.join(TEMPLATE_DIR, 'my-commit-template.hbs')
          )
        }
      }
    },
    '@semantic-release/changelog'
  ]
}
```

The plugin still uses the default `.hbs` templates from the `node_modules` folder.

I could provide a test repo if it's helpful. Let me know :)

**Comment by momocow** [comment]
I think the bug is introduced by mishandling those special types like function, Promises and Buffers while performing `_mergeWith` on the default config and the custom one. ([src](https://github.com/momocow/semantic-release-gitmoji/blob/master/lib/helper/get-config.js#L28))

Thanks for reporting the issue.

**Comment by momocow** [comment]
@thomasaull I can work on this issue now, can you provide a minimum repo to reproduce the problem? Thanks!

**Comment by thomasaull** [comment]
Yes, here it is: https://github.com/thomasaull/semantic-release-gitmoji-testrepo
Thansk for looking into this @momocow

**Comment by momocow** [comment]
@thomasaull Yet another busy week 😂. Sorry for the late response.

I finally found that the plugin has no problem but your configuration has mistaken the plugin option!
That is, you should wrap the plugin name and its option within an array.
[FYI](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#plugin-options)

```js
module.exports = {
  plugins: [
    [
      'semantic-release-gitmoji',
      {
        releaseNotes: {
          template: readFileAsync(
            path.join(TEMPLATE_DIR, 'my-default-template.hbs')
          ),
          partials: {
            commitTemplate: readFileAsync(
              path.join(TEMPLATE_DIR, 'my-commit-template.hbs')
            )
          }
        }
      }
    ],
    '@semantic-release/changelog'
  ]
}
```

After modification, it works like a charm.

**Comment by thomasaull** [comment]
Ha, years later, I can confirm it works like a charm. Thanks :)
