### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'semver')

### ISSUE THREAD

**Issue by bryanjtc** [momocow/semantic-release-gitmoji#57]
Upgrading to 1.6.0 throws the following error:
![image](https://user-images.githubusercontent.com/49354825/212371662-70954915-ca25-41e6-aa50-da664d9a3d0b.png)

**Comment by dgilperez** [comment]
I am having the same issue

**Comment by momocow** [comment]
OK, it seems that it is not an edge case. I'll merge this PR first for those who may be disturbed by this issue, but you can still provide what emoji you were using when facing this error to help locating possible issue.

**Comment by dgilperez** [comment]
Thanks for that! 

I am not sure which emoji failed in our case, the log wouldn't tell, but looking at the git log I see two we don't use often: `:safety_vest:` and `:see_no_evil:`. I am almost sure it is one of those.
