### ISSUE TITLE
option deactivate github requirement

### ISSUE THREAD

**Issue by ThommyH** [momocow/semantic-release-gitmoji#79]
I was trying to use the plugin to replace commit-analyser and found that it pulls github dependencies:

[semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"

The problem here is: we dont use github but rather gitlab. Therefore, the question: Are these dependencies required for the plugin to work at all? If not, is there a way to disable the dependency which allows us to make use of this plugin?

**Comment by momocow** [comment]
Hi, I think it is a dependency of `semantic-release` itself rather than this plugin.

[FYI](https://github.com/semantic-release/semantic-release/blob/c39513f24d8a72396848de2913c7a4a3c303ad32/package.json#L31)

**Comment by momocow** [comment]
Or check it on the NPM site:

https://www.npmjs.com/package/semantic-release?activeTab=dependencies

**Comment by ThommyH** [comment]
thanks, i figured it out
