### ISSUE TITLE
Help: how to get the description of each commit

### ISSUE THREAD

**Issue by arkadioz** [momocow/semantic-release-gitmoji#88]
I was trying to get the description of each commit but so far it has been not possible, I tried to check the docs here https://github.com/momocow/semantic-release-gitmoji?tab=readme-ov-file#commitcontext but the link to check the context inherited is [broken](https://github.com/semantic-release/semantic-release/blob/caribou/docs/developer-guide/js-api.md#commits), appreciate any help to print the description, here is my commit-template.hbs:

```
[`{{commit.short}}`](https://github.com/{{owner}}/{{repo}}/commit/{{commit.short}}) {{subject}} - desc: {{description}} {{this.description}} {{commit.description}} {{lookup this 'description'}} - author: {{this.author.name}} {{#if issues}}(Issues:{{#each issues}} [`{{text}}`]({{link}}){{/each}}){{/if}}
```

**Comment by momocow** [comment]
Please try `{{message}}` at the place you want to render commit descriptions.

**Comment by arkadioz** [comment]
@momocow Thanks, {{message}} it is working but it is giving me both the subject and description of the commit, is it possible to get only the description?

**Comment by arkadioz** [comment]
@momocow I found the docs that are broken, they were moved here: https://github.com/semantic-release/semantic-release/blob/master/docs/developer-guide/js-api.md

so to get only the commit description, {{body}} or {{this.body}} or {{commit.body}} can be used, thank you
