### ISSUE TITLE
How does the tool handles or behaves with reverts?

### ISSUE THREAD

**Issue by arkadioz** [momocow/semantic-release-gitmoji#95]
Hi @momocow hope you are doing well, I did a test recently where I reverted a already merged pull request that generated a new tag, and I ran the semantic-release but it didnt do anything (no new tag or anything), I believe this is okay I guess, but I also think that it is possible that you can configure at the release rules an emoji you want to use for revert commit message, so that when running the semantic-release after the revert you get a new tag right, but im not sure, what do you think is the correct behaviour??

Update:

Wanted to explain a little further, in bitbucket you can revert already Merged pull requests, and this allows you to set a commit message for the revert. So if you wanted the tool to do something it would be enough to configure a rule for the emoji you are going to use in that commit message, for example it could be the emoji ⬇️ for a patch, and you use this for any revert.

**Comment by momocow** [comment]
I would suggest this one, ⏪️, and configure it as a patch release rule.

https://github.com/carloscuesta/gitmoji/blob/ec01ecf3ccba63688d31af22a4dcf132bc7f3801/packages/gitmojis/src/gitmojis.json#L244-L251

**Comment by momocow** [comment]
> How does the tool handles or behaves with reverts?

Frankly speaking, it does nothing currently.

It only detect emojis and determine a new version, it's users responsibility to define any emoji to use in revert commits.

If there is any concern, please let me know, thank you!
