### ISSUE TITLE
update semantic-release peer to use > v23

### ISSUE THREAD

**Issue by mstruensee** [momocow/semantic-release-gitmoji#99]
are you able to do this?

**Comment by linuxidefix** [comment]
@mstruensee I created this PR: https://github.com/momocow/semantic-release-gitmoji/pull/100

**Comment by v1ack** [comment]
Hello @momocow 
Why https://github.com/momocow/semantic-release-gitmoji/pull/100 was reverted?
Actual version in npm is not working with latest semantic release

**Comment by linuxidefix** [comment]
The commit is still in main branch, but the new release has been rollbacked. No idea why

> Hello @momocow Why #100 was reverted? Actual version in npm is not working with latest semantic release

**Comment by momocow** [comment]
> Hello @momocow 
> 
> Why https://github.com/momocow/semantic-release-gitmoji/pull/100 was reverted?
> 
> Actual version in npm is not working with latest semantic release

Hi, sorry for any inconveniences.

The commit was rolled back in order to re-trigger the release pipeline because of Github token expiry.

But unluckily I haven't managed to make it work. I'll check any other solutions by tomorrow.

Thanks for reminding.

**Comment by v1ack** [comment]
@momocow there is a fun fact
It's semantic-release: 24.0.0 already 😅

**Comment by momocow** [comment]
Ha ha I see. lol

**Comment by momocow** [comment]
> @momocow there is a fun fact It's semantic-release: 24.0.0 already 😅

No worry, I've released a new patch, #102  🤣
